### ISSUE TITLE
Build folder missing

### ISSUE THREAD

**Issue by gowthamnatarajan** [rubenfiszel/webapp-rl4j#1]
Hi, I cant find Rl4j_Doom_Web_App folder to build this from. Where is it?

**Comment by rubenfiszel** [comment]
> Rl4j_Doom_Web_App

What is this folder ?

Ruben Fiszel

**Comment by gowthamnatarajan** [comment]
This folder is required in the build instructions for this project.

**Comment by rubenfiszel** [comment]
Oh sorry, my naming conventions are fairly inconsistent.
It's just the root folder: the folder in which you cloned this git repo.
